### ISSUE TITLE
Fix hardcoding of agent char as 'P'

### ISSUE THREAD

**Issue by eugenevinitsky** [eugenevinitsky/sequential_social_dilemma_games#85]
In the code it is hardcoded that agent cells are 'P'. If at any point we choose to change this, change amplification occurs and nearly the whole codebase needs to be rewritten.

**Comment by natashamjaques** [comment]
Could replace with a function called something like "check_if_agent_cell", that checks if the map character is an int, and > 0 (because I'm using agent IDs 1-9 on the map). Then instead of calling the function get_map_with_agents everywhere, we can just maintain the real map with the agent IDs in it. More computationally efficient.

**Comment by eugenevinitsky** [comment]
Eh, this is not a huge deal and makes rewriting the tests really frustrating.
